### PR TITLE
Questions 14-26

### PR DESCRIPTION
**Pull request by GregVoyzey**
Adding to my list of questions (14-26)

### CODE REVIEW

**Comment by GregVoyzey** [comment]
Added 14-26

**Comment by GregVoyzey** [comment]
I think my second pull request got merged ahead of this first pull request causing the conflict.

**Comment by Matt-Brigida** [comment]
Is it showing you the option to resolve conflicts?  If so you can simply delete what is repetitive between the <<<<<<< 
                     >>>>>>>

**Comment by GregVoyzey** [comment]
Removed the conflicts.  Does this need approved?

**Pull request merged**
